### ISSUE TITLE
Call entity extraction on save.

### ISSUE THREAD

**Issue by tomdyson** [tomdyson/entity-tagging-demo#2]
Call entity extraction function using relevant page content on save, using search fields, using the Blog Page model

**Comment by tomdyson** [comment]
Entity extraction function stubbed and ready to use at `master/bakerydemo/base/utils.py`.

**Comment by gasman** [comment]
Implemented in 13186451237d3d96c4bebf91b3dcbb691b613099. (The page's `full_clean` method is a suitable place for automatic field fixups like this, as it gets called on draft saves as well as on publish.)
